name: githubactionstrackr
description: A new Flutter project.
version: 1.0.0+5

publish_to: "none"
environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  align_positioned: ^1.2.6
  all_sensors: ^0.3.1+2
  ansicolor: 2.0.1
  auto_size_text: ^2.1.0
  background_fetch: ^1.1.0
  battery_plus: ^1.1.0
  cached_network_image: ^3.0.0
  computer: ^2.0.0
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.0
  device_info: ^2.0.0
  duration: ^2.0.15
  fading_edge_scrollview: ^1.1.4
  file_picker: 3.0.1
  # firebase_messaging: ^7.0.2
  flt_telephony_info:
    git:
      url: https://github.com/randomforest-jaant/flt_telephony_info.git
  flutter_apns:
    git:
      ref: bfe21166d31e15f40208d4ff8ca6cfb65f83c749
      url: https://github.com/OwnWeb/flutter-apns.git
  flutter_background_geolocation: ^4.7.0
  flutter_beep: ^0.2.0
  flutter_cache_manager: ^3.0.2
  flutter_compass:
    git:
      ref: 0304e1e8666edb74b9c2c71b16c4c7880d047c2d
      url: https://github.com/randomforest-jaant/flutter_compass.git
  flutter_dotenv: ^3.1.0
  flutter_image: ^3.0.0
  flutter_map: 0.13.1
  flutter_map_tile_caching: 3.0.3
  flutter_svg: 0.22.0
  flutter_xlider: ^3.4.0
  fluttertoast: ^8.0.6
  geocoding: ^2.0.0
  geolocator: ^5.1.3
  get_it: ^5.0.6
  health:
    git:
      path: packages/health
      ref: 00ffdd95416b3e4c79b0b4a88ec036463811eb81
      url: https://github.com/randomforest-jaant/flutter-plugins.git
  http: 0.13.3
  intl: ^0.17.0
  flutter_keyboard_visibility: ^5.2.0
  latlngconv:
    git:
      ref: 42ee8fa8c622d3444bac3624b7d4516e24de6630
      url: https://github.com/randomforest-jaant/dart-latlngconv.git
  loadany: ^1.0.0
  location: ^4.1.1
  material_segmented_control: ^2.1.1+1
  path_provider: ^2.0.1
  provider: ^4.3.3
  property_change_notifier:
    git:
      ref: 1a1cdd902898def8c75ddc69b3dec7a017645724
      url: https://github.com/martinrybak/property_change_notifier.git
  # resource_usage:
  #   path: ./plugins/resource_usage
  rxdart: 0.27.0
  sentry: 5.1.0
  share_extend: ^2.0.0
  shared_preferences: ^2.0.5
  sliding_up_panel: ^1.0.2
  sqflite: ^2.0.0+3
  sqflite_web:
    git:
      url: https://github.com/deakjahn/sqflite_web.git
      ref: 16350eaeaeee949db3c073cbc95a5e3f2880f096
  string_validator: ^0.1.4
  weather: ^2.0.1
  weather_icons:
    git:
      ref: tree-shaking-fix
      url: https://github.com/randomforest-jaant/weather_icons.git
  wifi_info_flutter: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  platform: ^3.1.0

flutter:
  uses-material-design: true
