name: "Buils(IOS) & upload to TestFlight"
on:
  push:
  release:
    types: [published]
jobs:
  build-ios:
    name: Build IOS
    runs-on: macos-latest
    env:
      flutter_version: 3.3.2
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: add java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "$flutter_version"
          channel: 'stable'