name: "Buils(IOS) & upload to TestFlight"
on:
  push:
  release:
    types: [published]
jobs:
  build-ios:
    name: Build IOS
    runs-on: macos-latest
    env:
      flutter_version: 3.3.2
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: add java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: echo flutter evrsion
        run: echo $flutter_version
      - name: Install flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $flutter_version
          channel: 'stable'
   
        name: Send Notification
        needs: release
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Echo Notification
          run: echo "Notificaton sent !" #TODO(skandar) send Notification via e-mail, Slack, Discord etc. if needed